src/Entity/Team.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
#[ApiResource]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $lastname = null;

    #[ORM\ManyToMany(targetEntity: Position::class, mappedBy: 'users')]
    #[Assert\NotBlank]
    private Collection $positions;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $year_old = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $tel = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $mail = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $CV = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $hierarchie = null;

    public function __construct()
    {
        $this->positions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Position>
     */
    public function getPositions(): Collection
    {
        return $this->positions;
    }

    public function addPosition(Position $position): static
    {
        if (!$this->positions->contains($position)) {
            $this->positions->add($position);
            $position->addUser($this);
        }

        return $this;
    }

    public function removePosition(Position $position): static
    {
        if ($this->positions->removeElement($position)) {
            $position->removeUser($this);
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getYearOld(): ?string
    {
        return $this->year_old;
    }

    public function setYearOld(string $year_old): static
    {
        $this->year_old = $year_old;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(string $CV): static
    {
        $this->CV = $CV;

        return $this;
    }

    public function getHierarchie(): ?string
    {
        return $this->hierarchie;
    }

    public function setHierarchie(string $hierarchie): static
    {
        $this->hierarchie = $hierarchie;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Team;
use Doctrine\ORM\EntityManagerInterface;

class DefaultController extends AbstractController
{
    private $em;
    private array $teamAll;

    // A l'instanciation de la class une requête est effectuer pour récupéré toute la table team
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
        $this->teamAll = $em->getRepository(Team::class)->findAll();
    }

    // La route avec le chemin de la page du controller et le nom de la route
    #[Route('/default', name: 'app_default')]
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            't_array' => $this->getTeam()
        ]);
    }

    #[Route('/model', name: 'app_model')]
    public function model_page(): Response
    {
        if (!isset($_GET['teamId']))
        {
            echo "<script>document.location.href='/'</script>";
        }else{

            $repo = $this->em->getRepository(Team::class);
            $team = $repo->find($_GET['teamId']);

            return $this->render('default/model.html.twig', [
                'team' => $team
            ]);
        }
    }

    // Fonction de récupération des valeurs de chaque collaborateur
    public function getTeam(): array
    {
        // Boucle du tableau du résultat de la requete précédament effectuer
        // t_value qui est égale a l'objet Team (App\Entity\Team)
        foreach ($this->teamAll as $t_value)
        {
            // Récupération des informations et stockage dans des variables
            $id = $t_value->getId();
            $firstname = $t_value->getFirstname();
            $lastname = $t_value->getLastname();
            $photo = $t_value->getPicture();
            $hierarchie = $t_value->getHierarchie();
            // $position lui est devenu, grâce au ManyToMany, l'objet Collection (Doctrine\Common\Collections\Collection)
            $position = $t_value->getPositions()->getValues();

            $key = $this->set_hierarchie($position[0]->getLabel(), $hierarchie);

            // compact créé un tableau depuis des variables avec le même nom qu'en paramètre et récupère les valeurs
            $t_array[$key] = compact('id', 'firstname', 'lastname', 'photo', 'hierarchie', 'position');
        }
        ksort($t_array, SORT_NUMERIC);
        return $t_array;
    }

    // Fonction de création de clés du tableau t_array en fonction du label de position de Team
    public function set_hierarchie($label, $hierarchie): int
    {
        switch ($label)
        {
            // Le gérant est forcément tout en haut
            case 'Gérant':
                $key = 1;
                break;
            // le premier chiffre de la clé est sa position
            case 'Lead dev':
                $key = 1000;
                break;
            case 'Commercial':
                $key = 2000;
                break;
            case 'Comptabilité':
                $key = 3000;
                break;
            // le deuxième chiffre est si il a un supérieur 
            case 'Dev':
                $key = 1100;
                if ($hierarchie == '3/1/2')
                {
                    // le troisième si il y a doublon
                    $key = 1110;
                }
                break;
            case 'UI/UX':
                $key = 1200;
                break;
            // le quatième si il y a un supérieur au supérieur
            case 'Testeur':
                $key = 1101;
                break;
            default:
                $key = 0;
                break;
        }
        return $key;
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acceuil{% endblock %}

{% block body %}

<div class="example-wrapper">

    {# Boucle du tableaux t_array envoyer du controller #}
    {% for key, team in t_array %}

        {# équivalent php "explode()" #}
        {% set hierarchie = team.hierarchie|split('/') %}

        {# Si le tableau hierarchie possède une ligne a l'index 0 #}
        {% if hierarchie[0] is defined %}
            {# same as() (équivalent php "===") #}
            {% if hierarchie[0] is same as('2') %}
                {# Alors création de variable className #}
                {% set className = 'deuxieme' %}

            {# Idem #}
            {% elseif hierarchie[0] is same as('3') %}
                {% set className = 'troisieme' %}
            {% elseif hierarchie[0] is same as('4') %}
                {% set className = 'quatrieme' %}

            {% endif %}
        {% endif %}
        {# Ouvreture d'un block <a> avec un attribut class qui si la variable className est defini alors appel de la variable className #}
        <div class="collab">
            <a class="collabs {% if className is defined %} {{className}} {% endif %}" href="model?teamId={{team.id}}">

            <img class="photo-profil" src="{{asset(team.photo)}}">{{team.firstname}} {{team.lastname}} ( {{team.position[0].getLabel()}}

            {# Boucle du tableau team.position #}
            {% for position in team.position %}
                {# Si l'index de la loop en partant de 0 est supérieur ou égal a 1 #}
                {% if loop.index0 >= 1 %}
                    {# Alors affichage des autres label #}
                    /{{team.position[loop.index0].getLabel()}}
                {% endif %}
            {% endfor %}
            {# Fermeture des parenthèses et de la balise <a> #}
            )</a>
        </div>

        {# équivalent php "var_dump()" #}
            {# {{dump(loop)}} #}
    {% endfor %}
</div>
{% endblock %}

templates/default/model.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page de {{team.firstname}} {{team.lastname}}{% endblock %}

{% block body %}
<a class="btn retour" href="/">Retour</a>
<a class="modifier" href="/form?teamId={{team.id}}">Modifier</a>
<div class="example-wrapper">

    <img src="{{asset(team.picture)}}">
    <p><strong>Nom:</strong> {{team.lastname}}</p>
    <p><strong>Prénom:</strong> {{team.firstname}}</p>
    <p><strong>Position:</strong> {{team.positions[0].getLabel()}}
    
        {# Boucle du tableau team.position #}
        {% for position in team.positions %}
            {# Si l'index de la loop en partant de 0 est supérieur ou égal a 1 #}
            {% if loop.index0 >= 1 %}
                /{{team.positions[loop.index0].getLabel()}}
            {% endif %}
        {% endfor %}
    </p>

    <p><strong>Age:</strong> {{team.yearOld}}</p>
    <p><strong>Adresse:</strong> {{team.adresse}}</p>
    <p><strong>Mobile:</strong> {{team.tel}}</p>
    <p><strong>Mail:</strong> <a href="#">{{team.mail}}</a></p>
    <p><strong>CV:</strong> <a href="{{asset(team.CV)}}">cv_{{team.lastname}}.pdf</a></p>

</div>
{% endblock %}